name: mager_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  http: ^1.2.0
  path: ^1.8.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/magerSpot.png"
  adaptive_icon_background: "#19253D"
  adaptive_icon_foreground: "assets/logoWhiteDua.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
